Provide different error messages in have_allvars depending on the variable status (undefined or empty)

diff --git a/initdefs b/initdefs
--- a/initdefs
+++ b/initdefs
@@ -16,6 +16,7 @@
 #
 # initdefs - 06/14/93
 #
+# initdefs - 09/19/2003 - jfs - Different error messages in have_allvars
 # initdefs - 08/13/2003 - jfs - Run_script now returns error number
 # initdefs - 08/09/2003 - jfs - Delete now checks if RM exists
 # initdefs - 08/08/2003 - jfs - Added safe_temp and run_script functions
@@ -77,10 +78,13 @@ haveallvars()
 
   for __var
   do
-    eval __val=\$$__var
-    if [ ! -n "$__val" ]; then
+    eval [ \"\${$__var+set}\" == \"\" ] || {
       echo "--ERROR-- [init007e] Don't have required variable $__var."
       __retval=1
+    }
+    if [ ! -n "$__val" ]
+    then
+      echo "--ERROR-- [init007e] Required variable $__var is empty."
     fi
   done
 
