Changes introduced in debian package 3.3.2-6:
  * Use /var/lib/tiger/work instead of /var/run/tiger/work to be
    FHS-compliant. It also avoids spamming people using a tmpfs /var/run
    with warning messages every time it creates its directory. (Closes: #486591)
  * Use tempfile in the config script to create the RC file if available, the
    $$ construct is used in a safe directory (WORKDIR) but this way people
    doing a cursory look at the code will not report (or try to fix, as in
    Ubuntu) inexistant temp race conditions.
  * Add a ignore for Debian to prevent Tiger from complaining about fetchmail
    processes.
  * Add additional samples for server processes to debian/server.ignore
  * Remove double linefeed in debian/changelog
  * Use UCF to handle configuration file changes to prevent prompting when
    upgrading to tiger versions that change the tigerrc. (Closes: #341595)
  * Remove stale left file created in /usr/lib/tiger/bin if it exists on purge
  * Lintian fixes:
       - Remove coreutils Depends as it is an Essential package
       - Remove code in postinst related to an ancient bug and associate
       debconf prompts.

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -1,8 +1,10 @@
 #!/bin/sh -e
 
+# System configuration file:
 CONFIG=/etc/tiger/tigerrc
+# Package-provided configuration file:
+PKGCONFIG=/usr/share/doc/tiger/examples/tigerrc.gz
 
-. /usr/share/debconf/confmodule
 test $DEBIAN_SCRIPT_DEBUG && set -v -x
 
 # summary of how this script can be called:
@@ -22,30 +24,35 @@ test $DEBIAN_SCRIPT_DEBUG && set -v -x
 #     installation fails and the `postinst' is called with `abort-upgrade',
 #     `abort-remove' or `abort-deconfigure'.
 
-remove_mess() {
-    # Do we have any tigerXX files under /var/log/? if so we should remove
-    # them. This were created due to bug #164682 ...
-    db_get tiger/remove_mess || true ; REMOVE="$RET"
-    [ "$REMOVE" = "true" ] && {
-	    find /var/log/ -type f -maxdepth 1 -name "tiger*" |xargs rm -f
-    }
-
-}
-
 case "$1" in
     install)
-    	remove_mess
     ;;
     upgrade)
-    	remove_mess
     ;;
     configure)
-	# edit config file
-	db_get tiger/mail_rcpt || true;	MAIL_RCPT="$RET"
-	test -f $CONFIG || touch $CONFIG
-	sed -e "s/^Tiger_Mail_RCPT=.*$/Tiger_Mail_RCPT=\"$MAIL_RCPT\"/" < $CONFIG > $CONFIG.$$
-        mv $CONFIG.$$ $CONFIG
-    	remove_mess
+	# Obtain the configured value
+        . /usr/share/debconf/confmodule
+	db_get tiger/mail_rcpt || true
+        MAIL_RCPT="$RET"
+
+        # Create temporary file for use in UCF
+        tempfile=`tempfile` || { echo "Cannot create temporary file, aborting" >&2; exit 1; }
+
+        # Determine if we are using a compressed configuration file or not
+        CAT=cat
+        if echo $PKGCONFIG | grep -q .gz; then
+            CAT=zcat
+        fi
+        if [ ! -e "$PKGCONFIG" ] ; then
+            echo "ERROR in maintainer script, cannot find package configuration file at $PKGCONFIG" >&2
+            exit 1
+        fi
+        $CAT $PKGCONFIG | sed -e "s/^Tiger_Mail_RCPT=.*$/Tiger_Mail_RCPT=\"$MAIL_RCPT\"/"  > $tempfile
+
+        # Use UCF to handle file changes
+        ucf $tempfile $CONFIG
+        ucfr tiger $CONFIG
+        rm -f $tempfile
     ;;
     abort-upgrade)
     ;;
@@ -55,9 +62,6 @@ case "$1" in
     ;;
 esac
 
-
-# dh_installdeb will replace this with shell code automatically
-# generated by other debhelper scripts.
 
 #DEBHELPER#
 
